### ISSUE TITLE
Usage example :

### ISSUE THREAD

**Issue by iradization** [lksnmnn/Symbolicate-CrashReports#2]
Hi, 

I'm currently looking to symbolicate some kernel panic log I've got. 
Currently I'm doing it manually .. for each address in the backtrace, I find within which driver range it's found, then I call that address with 'atos' in order to find it's matching function:line in the following manner : 

`atos -o <pathToDriverMacho> -l <driverBaseAddress> <addressFromBacktrace>`

the backtrace can contain several drivers involved, all are listed below with their corresponding address range : 

`
panic(cpu 0 caller 0xffffff800917ff59): "Releasing non-exclusive RW lock without a reader refcount!"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4570.51.1/osfmk/i386/locks_i386.c:1254
Backtrace (CPU 0), Frame : Return Address
0xffffff80690a3010 : 0xffffff800906e166 
0xffffff80690a3060 : 0xffffff8009196714 
0xffffff80690a30a0 : 0xffffff8009188a00 
0xffffff80690a3120 : 0xffffff8009020180 
0xffffff80690a3140 : 0xffffff800906dbdc 
0xffffff80690a3270 : 0xffffff800906d99c 
0xffffff80690a32d0 : 0xffffff800917ff59 
0xffffff80690a3300 : 0xffffff800918010e 
0xffffff80690a3320 : 0xffffff7f8a4621b0 
0xffffff80690a33f0 : 0xffffff7f8a4625cc 
0xffffff80690a3460 : 0xffffff7f8a43c4ba 
0xffffff80690a3540 : 0xffffff7f8a410152 
0xffffff80690a3d60 : 0xffffff80092cfa56 
0xffffff80690a3de0 : 0xffffff80092b6b74 
0xffffff80690a3f10 : 0xffffff80092b6da7 
0xffffff80690a3f40 : 0xffffff8009604418 
0xffffff80690a3fa0 : 0xffffff8009020966 
      Kernel Extensions in backtrace:
         com.apple.filesystems.apfs(748.51)[4E26C92D-330B-33A8-8DA7-C1498DD86AB7]@0xffffff7f8a3da000->0xffffff7f8a4bffff
            dependency: com.apple.kec.corecrypto(1.0)[CA65BD09-4559-3507-A72B-733ED9110DF1]@0xffffff7f89faf000
            dependency: com.apple.driver.AppleEffaceableStorage(1.0)[6B49B846-2852-3D7C-BD45-E70DC2684A8E]@0xffffff7f8a33e000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[F27A8A2A-6662-3608-83BD-415037509E01]@0xffffff7f89ab7000
`

it seems like this script perform this routine automatically. but doesn't come with usage example, perhaps you can provide one ? 

thanks

**Comment by lksnmnn** [comment]
I do not know if this script actually symbolicates Apples system routines. Basically this is just a copy of Apples own `symbolicate.sh` which is packaged within Xcode and I added some code to be able to symbolicate Mac and iOS crash reports created with PLCrashReporter.

It could even be, that Apple updated their symbolication script and fixed some of the issues this version (from 2016) has. Since I am currently not working on iOS or Mac applications and have little to no time to update and fix this script.

As for an usage example. Take a look at the Readme.md section _Usage_: https://github.com/lksnmnn/Symbolicate-CrashReports#usage
